apiVersion: v1
entries:
  etl:
  - apiVersion: v2
    created: "2021-12-13T16:43:05.743898-05:00"
    description: A Helm chart for Kubernetes to run Supercluster ETL as cronjob
    digest: 5917b3fd5b3538c3ad42cac01a3b009d363fb6cd74fc37d5ad169c9df65d3411
    name: etl
    type: application
    urls:
    - https://supercluster-covid-data-portal.github.io/charts/etl-0.1.0.tgz
    version: 0.1.0
generated: "2021-12-13T16:43:05.740226-05:00"
