apiVersion: batch/v1beta1
kind: CronJob

metadata:
  name: {{ include "etl.fullname" . }}
  labels:
    {{- include "etl.labels" . | nindent 4 }}
    {{- include "etl.customLabels" . | nindent 4 }}

spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "etl.labels" . | nindent 12 }}
            {{- include "etl.customLabels" . | nindent 12 }}
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }} 
            args:
              - sh
              - -c
              - node etl --all
            env: 
{{- if .Values.extraEnv }} 
  {{- range $key, $value := .Values.extraEnv }}
              - name: {{ $key }}
                value: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- with .Values.extraEnvYaml }}
              {{- toYaml . | nindent 14 }}
{{- end }}
            ports:
              - containerPort: {{ .Values.service.internalPort }} 
          restartPolicy: {{ .Values.restartPolicy }}
          imagePullSecrets:
            - name: artifactory 